services:
  # A Docker web service
  - type: web
    name: express-api
    env: node
    repo: https://github.com/danyalasif/express-angular # optional
    region: oregon # optional (defaults to oregon)
    plan: starter # optional (defaults to starter instance type)
    branch: main # optional (defaults to master)
    rootDir: .
    numInstances: 1 # optional (defaults to 1)
    healthCheckPath: /
    buildCommand: npm install; npm run api:build
    startCommand: node apps/api/dist/main.js
